# -*- coding: utf-8 -*-
"""AIニュース用

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B8Yqpyos50nhN8YxKg2pmQ7A-BBepk7V
"""

import feedparser
import openai
from slack_sdk.webhook import WebhookClient
import os

# --- APIキーはGitHub Secretsから取得 ---
openai.api_key = os.getenv("OPENAI_API_KEY")
slack_webhook_url = os.getenv("SLACK_WEBHOOK_URL")

# --- ニュース収集（RSSから取得） ---
def fetch_rss(feed_url, max_items=2):
    feed = feedparser.parse(feed_url)
    articles = []
    for entry in feed.entries[:max_items]:
        articles.append({
            "title": entry.title,
            "link": entry.link,
            "summary": entry.get("summary", "") or entry.get("description", "")
        })
    return articles

# --- GPTによる要約（RSS記事用） ---
def summarize_article(article_text):
    prompt = f"""
以下の記事を「Indeedクライアントサクセス担当者が社内共有するニュースサマリー」として要約してください。

出力フォーマットは必ず日本語で以下にしてください：
📰 タイトル
✅ 世の中はどう変わるか？
👉 採用・人材業界への影響は？
🟢 クライアントに伝えるべきこと（具体的な例）
💡 Indeedクライアントサクセス（CS）としてのアクション
🔑 それでもIndeedに期待される役割（求人の信頼性・AI時代のサポートなど）
"""

    response = openai.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt + article_text}],
        temperature=0.5,
    )
    return response.choices[0].message.content



# --- GPTニュース補足（検索ベース） ---
def fetch_gpt_news():
    prompt = """
    今日のAI関連ニュースを3件まとめてください。
    それぞれについて：
    - タイトル
    - 要点のまとめ（100文字以内）
    - 出典URL（信頼できるソースを1つ探して提示）
    を必ず含めてください。
    日本語で出力してください。
    """
    res = openai.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.5,
    )
    return res.choices[0].message.content

# --- Slack投稿 ---
def post_to_slack(title, summary, link):
    webhook = WebhookClient(slack_webhook_url)
    message = f"""
*📰 {title}*
{summary}

🔗 <{link}|記事はこちら>
"""
    webhook.send(text=message)


# --- メイン処理 ---
if __name__ == "__main__":
    rss_urls = [
        # 🌍 海外
        "https://techcrunch.com/tag/artificial-intelligence/feed/",
        "https://venturebeat.com/category/ai/feed/",
        "https://www.technologyreview.com/feed/",
        "https://www.theverge.com/artificial-intelligence/rss/index.xml",
        "http://feeds.bbci.co.uk/news/technology/rss.xml",

        # 🇯🇵 国内
        "https://www.nikkei.com/rss/technology.rdf",
        "https://rss.itmedia.co.jp/rss/2.0/news_bursts.xml",
        "https://www.hrpro.co.jp/rss/"
    ]

    # --- RSSニュース配信 ---
    for url in rss_urls:
        articles = fetch_rss(url, max_items=2)
        for article in articles:
            print(f"処理中: {article['title']}")
            summary = summarize_article(article["summary"] or article["title"])
            post_to_slack(article["title"], summary, article["link"])
            print("Slackに送信しました ✅")

    # --- GPTニュース補足 ---
    print("GPTニュースを取得中...")
    gpt_news = fetch_gpt_news()
    post_to_slack("🧠 GPTニュース補足", gpt_news, "https://chat.openai.com/")
    print("GPTニュースをSlackに送信しました ✅")